table "source.test_db.changes" [gridX: 0] {
   "changeid" NUMBER
   "change_type" TEXT
   Note: "BASE TABLE"
}

//ref: source.test_db.changes - basic.test_db.users

table "basic.test_db.users" [gridX: 1] {
   "userid" NUMBER
   "name" TEXT
   "occupation" TEXT
   Note: "VIEW"
}

//ref: source.test_db.changes - basic.test_db.users
